services:
  confluence-postgres_1:
    image: ${POSTGRES_CONTAINER}
    container_name: confluence-postgres_1
    environment:
      POSTGRES_DATABASE: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      - default
    ports:
      - "5433:5432"
    volumes:
      - postgresVolume:/var/lib/postgresql/data
    ulimits:
      nproc: 65535
      nofile:
        soft: 32000
        hard: 40000

  confluence_1:
    image: ${CONTAINER_ID_CONFLUENCE}
    container_name: confluence_1
    depends_on:
      - confluence-postgres_1
    environment:
      JVM_MINIMUM_MEMORY: "4096M"
      JVM_MAXIMUM_MEMORY: "4096M"
      ATL_PROXY_NAME: "${HOST_NAME_CONFLUENCE}"
      ATL_PROXY_PORT: 443
      ATL_TOMCAT_SCHEME: "https"
      ATL_TOMCAT_SECURE: "true"
      ATL_JDBC_URL: "jdbc:postgresql://confluence-postgres_1:5432/confluence"
      ATL_JDBC_USER: "${POSTGRES_USER}"
      ATL_JDBC_PASSWORD: "${POSTGRES_PASSWORD}"
      ATL_DB_TYPE: "postgresql"
      ATL_LICENSE_KEY: "${CONFLUENCE_LICENSE}"
    expose:
      - "8080"
    networks:
      - web
      - default
    volumes:
      - confluenceVolume:/var/atlassian/application-data/confluence

  metabase:
    image: metabase/metabase:latest
    depends_on:
      - confluence-postgres_1
    ports:
      - 3000:3000
    networks:
      - web
      - default
  caddy:
    container_name: caddy_1
    image: caddy:latest
    networks:
      - web
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./Caddyfile:/etc/caddy/Caddyfile"
    restart: unless-stopped

networks:
  web:
    external: true
volumes:
  confluenceVolume:
  postgresVolume:
